In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import bqplot
import ipywidgets 
%matplotlib inline

## Data preprocessing

The dashboard here is used to explore the relationship between different factors, e.g: number of bathrooms, kitchens, square,etc, and show its time variation. 

First, the year and month will be extracted from trade time column and add to the dataframe as two new columns. 
Then add a new column for square to divide it into several sections.

In [2]:
# general description
house_price = pd.read_csv('house_price.csv', ',',encoding = 'unicode_escape', low_memory=False)
house_price['square'].describe()

count    299133.000000
mean         83.098062
std          36.956223
min           7.370000
25%          57.950000
50%          74.100000
75%          98.530000
max        1745.500000
Name: square, dtype: float64

In [3]:
# extract year and month
house_price['Year'] = house_price['tradeTime'].str[0:4].astype('int64')
# house_price['month'] = house_price['tradeTime'].str[5:6].astype('int64') only extract one digit month number, 10 -1, 11-1,12-1
house_price['month'] = house_price['tradeTime'].str[5:7]
house_price['month'] = house_price['month'].str.replace('/', '').astype('int64')
house_price

,Lng,Lat,tradeTime,totalPrice,price,square,livingRoom,drawingRoom,kitchen,bathRoom,floor,buildingType,constructionTime,renovationCondition,ladderRatio,elevator,subway,district,Year,month
0,116.475489,40.019520,2016/8/9,415.0,31680,131.00,2,1,1,1,26,1.0,2005,3,0.217,1.0,1.0,7,2016,8
1,116.453917,39.881534,2016/7/28,575.0,43436,132.38,2,2,1,2,22,1.0,2004,4,0.667,1.0,0.0,7,2016,7
2,116.561978,39.877145,2016/12/11,1030.0,52021,198.00,3,2,1,3,4,4.0,2005,3,0.500,1.0,0.0,7,2016,12
3,116.438010,40.076114,2016/9/30,297.5,22202,134.00,3,1,1,1,21,1.0,2008,1,0.273,1.0,0.0,6,2016,9
4,116.428392,39.886229,2016/8/28,392.0,48396,81.00,2,1,1,1,6,4.0,1960,2,0.333,0.0,1.0,1,2016,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299128,116.546899,39.755236,2016/6/9,355.5,26491,134.20,3,2,1,2,9,3.0,2009,4,0.500,1.0,0.0,3,2016,6
299129,116.546899,39.755236,2016/6/10,350.0,20580,170.07,3,2,1,2,5,4.0,2003,1,0.333,0.0,0.0,3,2016,6
299130,116.497474,39.810115,2016/6/10,108.8,31006,35.09,1,0,1,1,24,1.0,2009,1,0.222,1.0,1.0,3,2016,6
299131,116.497256,39.804081,2016/6/5,359.0,35138,102.17,2,2,1,2,7,4.0,2000,3,0.500,1.0,0.0,3,2016,6
299132,116.501794,39.799347,2016/6/12,720.0,40373,178.34,4,2,1,2,5,4.0,2003,4,0.500,0.0,0.0,3,2016,6

In [4]:
# change continous values of square to a set of ranges
bins = [0,30,50,70,90,110,150, 200,500,1000]
labels = ['0-30', '30-50', '50-70', '70-90', '90-110', '110-150', '150-200', '200-500', '500-1000']
house_price['squareRange'] = pd.cut(house_price['square'],bins, labels=labels)
# house_price[(house_price['drawingRoom']== 1) & (house_price['Year']== 2012)]['month'].unique()
house_price

,Lng,Lat,tradeTime,totalPrice,price,square,livingRoom,drawingRoom,kitchen,bathRoom,...,buildingType,constructionTime,renovationCondition,ladderRatio,elevator,subway,district,Year,month,squareRange
0,116.475489,40.019520,2016/8/9,415.0,31680,131.00,2,1,1,1,...,1.0,2005,3,0.217,1.0,1.0,7,2016,8,110-150
1,116.453917,39.881534,2016/7/28,575.0,43436,132.38,2,2,1,2,...,1.0,2004,4,0.667,1.0,0.0,7,2016,7,110-150
2,116.561978,39.877145,2016/12/11,1030.0,52021,198.00,3,2,1,3,...,4.0,2005,3,0.500,1.0,0.0,7,2016,12,150-200
3,116.438010,40.076114,2016/9/30,297.5,22202,134.00,3,1,1,1,...,1.0,2008,1,0.273,1.0,0.0,6,2016,9,110-150
4,116.428392,39.886229,2016/8/28,392.0,48396,81.00,2,1,1,1,...,4.0,1960,2,0.333,0.0,1.0,1,2016,8,70-90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299128,116.546899,39.755236,2016/6/9,355.5,26491,134.20,3,2,1,2,...,3.0,2009,4,0.500,1.0,0.0,3,2016,6,110-150
299129,116.546899,39.755236,2016/6/10,350.0,20580,170.07,3,2,1,2,...,4.0,2003,1,0.333,0.0,0.0,3,2016,6,150-200
299130,116.497474,39.810115,2016/6/10,108.8,31006,35.09,1,0,1,1,...,1.0,2009,1,0.222,1.0,1.0,3,2016,6,30-50
299131,116.497256,39.804081,2016/6/5,359.0,35138,102.17,2,2,1,2,...,4.0,2000,3,0.500,1.0,0.0,3,2016,6,90-110
299132,116.501794,39.799347,2016/6/12,720.0,40373,178.34,4,2,1,2,...,4.0,2003,4,0.500,0.0,0.0,3,2016,6,150-200

The purpose of this dashboard is to explore the relationship between price and other factors that may influence the price. The colormap represent the trade time from 2011 to 2017. The light color represent for the earlier days of tradetime.

In [5]:
# a quick plot of each columns vs price 
@ipywidgets.interact(x = ['Lng', 'square', 'livingRoom', 'drawingRoom', 'kitchen', 'bathRoom', 'floor', 'buildingType', \
                          'constructionTime', 'renovationCondition', 'ladderRatio', 'elevator', 'subway', 'district'],
                     y = [ 'Lat', 'price'])

def plot(x,y): 
    x_column = house_price[x]
    y_column = house_price[y]
    fig,ax = plt.subplots(figsize=(20,10))
    ax = plt.scatter(x_column,y_column, c=house_price['Year'])
    plt.xlabel(x)
    plt.ylabel(y)
    if x == 'Lng' and y == 'Lat':
        plt.title('House location map')
    else:
        plt.title('The influence of {} on {}'.format(x,y))
    plt.show()

interactive(children=(Dropdown(description='x', options=('Lng', 'square', 'livingRoom', 'drawingRoom', 'kitche…

In [6]:
total_price = house_price.groupby('month')['price'].mean()
total_price

month
1     42723.545402
2     47134.748801
3     45651.903510
4     41508.385224
5     40661.658258
6     40296.782522
7     43076.085678
8     45089.032593
9     47411.456337
10    42035.296842
11    43164.836988
12    44194.706638
Name: price, dtype: float64

The dashboard can develop the price influence by years and the other influence factor.

In [7]:
house_matrix = house_price.pivot_table(index = 'Year', columns='kitchen', values = 'price')
house_matrix

kitchen             0             1             2             3
Year
2011     15206.748299  21817.329719  23496.125000  23826.333333
2012     23135.757785  25939.071897  25524.224299  33108.500000
2013     29079.034921  35013.446544  32684.691489  20019.000000
2014     32303.990868  37169.352312  31483.791209           NaN
2015     36630.176781  38816.377574  40728.908451  51134.500000
2016     46673.390048  50651.900797  50369.590909  40725.800000
2017     53448.156489  67306.278454  68655.315315  46340.000000

Build heatmap and linked line plot first and check whether it works well.

In [8]:
# # CRATE LABEL - # 1
# mySelectedLable = ipywidgets.Label()

In [9]:
# # x and y data
# x = house_matrix.index
# y = house_matrix.columns

# # decide which scale to use after data input

# # scales 
# x_sc = bqplot.OrdinalScale()
# y_sc = bqplot.LinearScale()
# col_sc = bqplot.ColorScale(schema='RdPu')

# # axis 
# x_ax = bqplot.Axis(scale=x_sc, label='Kitchen',  tick_style = {'font-size': 8})
# y_ax = bqplot.Axis(scale=y_sc, label='Year', orientation='vertical',  tick_style = {'font-size': 8})
# c_ax = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right')

# # marks
# heat_map = bqplot.GridHeatMap(color= house_matrix, 
#                               row= x.tolist(), 
#                               column= y.tolist(),
#                              scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
#                              interactions={'click':'select'},
#                              anchor_style={'fill':'blue'})

In [10]:
# # create plot elemetns 
# x_scl = bqplot.LinearScale()
# y_scl = bqplot.LinearScale() 

# ax_xcl = bqplot.Axis(label='Month',scale=x_scl) # dates
# ax_ycl = bqplot.Axis(label='Price', scale=y_scl,
#                      orientation='vertical', side='left')

# line = bqplot.Lines(x= total_price.index,
#                    y = total_price,
#                    scales = {'x':x_scl, 'y':y_scl})

# fig = bqplot.Figure(axes=[ax_xcl, ax_ycl], marks=[line])

In [11]:
# # link lineplot with heatmap 
# def get_data_value(change):
#     # to make sure we only support single selections 
    
#     if len(change['owner'].selected) == 1: # only one selection
# #         print(change['owner'].selected)
#         i,j = change['owner'].selected[0]
#         v = house_matrix.iloc[i, j] 
# #         print(v)
#         if v >0:
#             mySelectedLable.value = 'price=' + str(v)
# #             print(house_matrix.index[i])
# #             print(house_matrix.columns[j])

#             # get the value of the corresponding x and year in heatmap for columns match 
#             year = house_matrix.index[i]
#             kitchen = house_matrix.columns[j]

#             df_price = house_price[(house_price[column]== kitchen) & (house_price['Year']== year)]
# #             print(df_price)
#             total_price = df_price.groupby('month')['price'].mean()
# #             print(total_price.index)

#             line.x = total_price.index
#             line.y = total_price
        
        
# # make sure to observe the change         
# heat_map.observe(get_data_value, 'selected')

In [12]:
# # create figure objects
# fig_heatmap = bqplot.Figure(marks=[heat_map], axes = [c_ax, y_ax, x_ax],fig_margin={'top':20, 'bottom':100, 'left':150, 'right':100})
# fig_line = bqplot.Figure(marks=[line], axes = [ax_xcl, ax_ycl],fig_margin={'top':20, 'bottom':100, 'left':60, 'right':60})

In [13]:
# # format dashboard
# fig_heatmap.layout.min_width = '400px'
# fig_line.layout.min_width = '400px'

# plots = ipywidgets.HBox([fig_heatmap, fig_line])
# myDashboard = ipywidgets.VBox([mySelectedLable, plots])
# myDashboard

Impove the dashbaord by allowing the user to change the combination of heatmap.The user can explore the influence of different factors to the house price. The price axis is not changed.

Though the first idea is to make a linked dashboard which the x and y axis can both decided by the user. I tried to make the heat map showing not only year for its vertical axis. But something went wrong when plotting the line plot. Then the second idea is to keep the vertical axis of heatmap to be different years, change the horizontal axis. And the line plot keeps plotting the price changes in different months.

In [14]:
# # CRATE LABEL - # 1
# mySelectedLable = ipywidgets.Label()

In [15]:
# # link lineplot with heatmap 
# def get_data_value(change):
#     # to make sure we only support single selections 
    
#     if len(change['owner'].selected) == 1: # only one selection
# #         print(change['owner'].selected)
#         i,j = change['owner'].selected[0]
# #         print(i,j)
#         v = house_matrix.iloc[i, j] 
        
#         if v >0:
#             mySelectedLable.value = 'price=' + str(v)

#             # get the value of the corresponding x and year in heatmap for columns match 
#             index = house_matrix.index[i]
# #             print(index)
#             column = house_matrix.columns[j]
# #             print(column)
# #             print(column_x)
# #             print(column_y)
#             df_price = house_price[(house_price[column_y]== column) & (house_price[column_x]== index)]
# #             print(df_price)
            
#             # group by each month 
#             month_price = df_price.groupby('month')['price'].mean()
            
# #             print(total_price.index)

#             line.x = month_price.index
#             line.y = month_price

In [16]:
# @ipywidgets.interact(x = ['Year'],
#                      y = [ 'squareRange','livingRoom', 'drawingRoom', 'kitchen', 'bathRoom', 'floor', 'buildingType', \
#                            'renovationCondition',  'elevator', 'subway', 'district'])
# def dashboard(x,y):
#     # global the variables so that it can be passed into get_data_value function 
#     global house_matrix
#     global line
    
#     global column_y
#     global column_x
#     column_y = y
#     column_x = x
    
#     house_matrix = house_price.pivot_table(index = x, columns= y, values = 'price')
#     total_price = house_price.groupby('month')['price'].mean()


#     # create heatmap elements
#     # x and y data
#     x = house_matrix.index
#     y = house_matrix.columns


#     # scales 
#     x_sc = bqplot.OrdinalScale()
#     y_sc = bqplot.OrdinalScale()
#     col_sc = bqplot.ColorScale(schema='RdPu')

#     # axis 
#     x_ax = bqplot.Axis(scale=x_sc, label= y.name ,tick_rotate = 90,tick_style = {'font-size': 8})
#     y_ax = bqplot.Axis(scale=y_sc, label= x.name, orientation='vertical',  tick_style = {'font-size': 8})
#     c_ax = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right')

#     # marks
#     heat_map = bqplot.GridHeatMap(color= house_matrix, 
#                                   row= x.tolist(), 
#                                   column= y.tolist(),
#                                  scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
#                                  interactions={'click':'select'},
#                                  anchor_style={'fill':'blue'})
    
#     # create line plot elemetns 
#     x_scl = bqplot.LinearScale()
#     y_scl = bqplot.LinearScale() 

#     ax_xcl = bqplot.Axis(label='month',scale=x_scl) # dates
#     ax_ycl = bqplot.Axis(label='Price', scale=y_scl,
#                          orientation='vertical', side='left')

#     line = bqplot.Lines(x= total_price.index,
#                        y = total_price,
#                        scales = {'x':x_scl, 'y':y_scl})

    
#     # make sure to observe the change  
#     heat_map.observe(get_data_value, 'selected')
    
    
#     # create figure objects for both plots
#     fig_heatmap = bqplot.Figure(marks=[heat_map], axes = [c_ax, y_ax, x_ax],fig_margin={'top':20, 'bottom':50, 'left':150, 'right':100})
#     fig_line = bqplot.Figure(marks=[line], axes = [ax_xcl, ax_ycl],fig_margin={'top':20, 'bottom':50, 'left':60, 'right':60})

#     # format dashboard
#     fig_heatmap.layout.min_width = '400px'
#     fig_line.layout.min_width = '400px'

#     plots = ipywidgets.HBox([fig_heatmap, fig_line])
#     myDashboard = ipywidgets.VBox([mySelectedLable, plots])
#     return myDashboard

It seems that there is no trade records after September in the dataset. And I'll explore it in the following steps.

In [17]:
# house_price[(house_price['drawingRoom']== 1) & (house_price['Year']== 2012)]['month'].unique()
# house_price[(house_price['squareRange']== '90-110') & (house_price['Year']== 2011)]['month'].unique()

The previous dashboard x and y axis need to be exchanged for some mistakes.

In [18]:
# CRATE LABEL - # 1
mySelectedLable = ipywidgets.Label()

In [19]:
# link lineplot with heatmap 
def get_data_value(change):
    # to make sure we only support single selections 
    
    if len(change['owner'].selected) == 1: # only one selection
#         print(change['owner'].selected)
        i,j = change['owner'].selected[0]
#         print(i,j)
        v = house_matrix.iloc[i, j] 
        
        if v >0:
            mySelectedLable.value = 'price=' + str(v)

            # get the value of the corresponding x and year in heatmap for columns match 
            index = house_matrix.index[i]
#             print(index)
            column = house_matrix.columns[j]
#             print(column)
#             print(column_x)
#             print(column_y)
            df_price = house_price[(house_price[column_x]== column) & (house_price['Year']== index)]
#             print(df_price)
            
            # group by each month 
            month_price = df_price.groupby('month')['price'].mean()
            
#             print(total_price.index)

            line.x = month_price.index
            line.y = month_price

In [20]:
@ipywidgets.interact(
                     column = [ 'squareRange','livingRoom', 'drawingRoom', 'kitchen', 'bathRoom', 'floor', 'buildingType', \
                           'renovationCondition',  'elevator', 'subway', 'district'])
def dashboard(column):
    # global the variables so that it can be passed into get_data_value function 
    global house_matrix
    global line
    
    global column_x

    column_x = column
# 
    
    house_matrix = house_price.pivot_table(index = 'Year', columns= column, values = 'price')
    total_price = house_price.groupby('month')['price'].mean()


    # create heatmap elements
    # x and y data
    x = house_matrix.index
    y = house_matrix.columns


    # scales 
    x_sc = bqplot.OrdinalScale()
    y_sc = bqplot.OrdinalScale()
    col_sc = bqplot.ColorScale(schema='RdPu')

    # axis 
    x_ax = bqplot.Axis(scale=x_sc, label= column ,tick_rotate = 90,tick_style = {'font-size': 8})
    y_ax = bqplot.Axis(scale=y_sc, label= 'Year', orientation='vertical',  tick_style = {'font-size': 8})
    c_ax = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right')

    # marks
    heat_map = bqplot.GridHeatMap(color= house_matrix, 
                                  row= x.tolist(), 
                                  column= y.tolist(),
                                 scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                                 interactions={'click':'select'},
                                 anchor_style={'fill':'blue'})
    
    # create line plot elemetns 
    x_scl = bqplot.LinearScale()
    y_scl = bqplot.LinearScale() 

    ax_xcl = bqplot.Axis(label='month',scale=x_scl) # dates
    ax_ycl = bqplot.Axis(label='Price', scale=y_scl,
                         orientation='vertical', side='left')

    line = bqplot.Lines(x= total_price.index,
                       y = total_price,
                       scales = {'x':x_scl, 'y':y_scl})

    
    # make sure to observe the change  
    heat_map.observe(get_data_value, 'selected')
    
    
    # create figure objects for both plots
    fig_heatmap = bqplot.Figure(marks=[heat_map], axes = [c_ax, y_ax, x_ax],fig_margin={'top':20, 'bottom':50, 'left':150, 'right':100})
    fig_line = bqplot.Figure(marks=[line], axes = [ax_xcl, ax_ycl],fig_margin={'top':20, 'bottom':50, 'left':60, 'right':60})

    # format dashboard
    fig_heatmap.layout.min_width = '400px'
    fig_line.layout.min_width = '400px'

    plots = ipywidgets.HBox([fig_heatmap, fig_line])
    myDashboard = ipywidgets.VBox([mySelectedLable, plots])
    return myDashboard

interactive(children=(Dropdown(description='column', options=('squareRange', 'livingRoom', 'drawingRoom', 'kit…

The dashboard above is used to describe the average house trade price in different year filtered by different influence factors. To some extent is reflect how the factor will increase/decrease house price as time going. The columns can be chaged in the dropdown menu, temproraily, for vertical axis, only year is accepted. 

The left side heatmap:
* It represents the average price in each year under the certain condition, for example, the average price in 2016 under the square range 90-110. 
* The blue area is the selected area, which the further data will be plotted on right hand side line plot.

The right side plot:
* By clicking on the heatmap, the righ hand side line plot will change, which reflect the corresponding average house price each month in that year of the blue selection area .

List of dataset: 
* Name of Dataset: Airbnb Beijing 20190211
* URL: https://www.kaggle.com/merryyundi/airbnb-beijing-20190211/download
* This dataset includes the airbnb price and the trade data in Bejing from 2008, which may help reflect the hosue price changes in Bejing.